paragraph = ("""
The Sun is a colossal, self-gravitating sphere of incandescent plasma that serves as the 
ultimate engine of our solar system. As a G-type main-sequence star, it maintains a delicate 
balance between the inward crush of its own gravity and the outward pressure generated by 
nuclear fusion in its core. Every second, the Sun fuses approximately 600 million tons of 
hydrogen into helium, a process that converts mass into pure energy according to Einstein’s 
famous equation, $E = mc^2$. This energy migrates from the core through the radiative and 
convective zones over hundreds of thousands of years before finally being emitted from the 
photosphere as the sunlight we see on Earth.
""")

# Find Total words into paragraph

words = paragraph.split()
print(f"Words {len(words)}")

# Find the total number of words that have 2 characters 

two_character_word_count = 0
for word in words :
    if len(word) == 2 :
       two_character_word_count += 1

print(f"2 character words {two_character_word_count}")
       
# Find the total number of words that has more then 2 characters and less then 5 characters

five_less_2_more_word_count = 0

for word in words :
    if len(word) > 2 and len(word) < 5 :
        five_less_2_more_word_count += 1

print(f"5 letter less and 2 letter more {five_less_2_more_word_count}")

# Find the word with maximum characters 

biggest_word = ""
biggest_word_length = 0

for word in words : 
    current_word_length = len(word)
    if biggest_word_length < current_word_length:
        biggest_word_length = current_word_length
        biggest_word = word

print(f"The largest word is {biggest_word} it has {biggest_word_length} characters")

# Find the number of odd and even words

even_word_count = 0
odd_word_count = 0

for word in words :
    if len(word) % 2 == 0 :
        even_word_count += 1
    else :
        odd_word_count += 1

print(f"There are the amount of even words {even_word_count}")
print(f"There are the amount of odd words {odd_word_count}")

# Find the number of words that have 't' or 'T' in them

words_with_t_count = 0

for word in words :
    if "t" in word or "T" in word :
        words_with_t_count += 1

print(f"{words_with_t_count} words have t or T ")